"""Add wants_point_notifications to User model

Revision ID: 3244bacf9534
Revises: ccbaaf7662b7
Create Date: 2025-10-07 01:57:43.321695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3244bacf9534'
down_revision = 'ccbaaf7662b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wants_point_notifications', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_column('wants_point_notifications')
    # ### end Alembic commands ###