"""Add order notification preference

Revision ID: 60f2906749db
Revises: 3244bacf9534
Create Date: 2025-10-07 02:41:41.959952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f2906749db'
down_revision = '3244bacf9534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wants_order_notifications', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_column('wants_order_notifications')

    # ### end Alembic commands ###