"""Add WishlistItem model

Revision ID: 65f94b714712
Revises: 988d6fbccf58
Create Date: 2025-10-07 03:46:38.799752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65f94b714712'
down_revision = '988d6fbccf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WISHLIST_ITEMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.USER_CODE'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.drop_table('Points')
    op.drop_table('Organizations')
    op.drop_table('Users')
    with op.batch_alter_table('ABOUT_INFO', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=mysql.TINYTEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('ADMIN', schema=None) as batch_op:
        batch_op.alter_column('ROLE_TITLE',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.alter_column('DRIVER_ID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('SPONSOR_ID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('APPLIED_AT',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('NOTIFICATIONS', schema=None) as batch_op:
        batch_op.alter_column('MESSAGE',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('READ_STATUS',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('SPONSORS', schema=None) as batch_op:
        batch_op.alter_column('ORG_NAME',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('USERNAME',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('FNAME',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('LNAME',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('EMAIL',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('CREATED_AT',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('IS_ACTIVE',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('IS_LOCKED_OUT',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.create_unique_constraint(None, ['USERNAME'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('IS_LOCKED_OUT',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('IS_ACTIVE',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('CREATED_AT',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('EMAIL',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('LNAME',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('FNAME',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('USERNAME',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)

    with op.batch_alter_table('SPONSORS', schema=None) as batch_op:
        batch_op.alter_column('ORG_NAME',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('NOTIFICATIONS', schema=None) as batch_op:
        batch_op.alter_column('READ_STATUS',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
        batch_op.alter_column('MESSAGE',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)

    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.alter_column('APPLIED_AT',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('SPONSOR_ID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('DRIVER_ID',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ADMIN', schema=None) as batch_op:
        batch_op.alter_column('ROLE_TITLE',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('ABOUT_INFO', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=255),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)

    op.create_table('Users',
    sa.Column('User_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('User_Fname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('User_Lname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('User_Role', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('User_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Organizations',
    sa.Column('Org_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Org_Name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Org_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Points',
    sa.Column('User_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Points_Value', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['User_ID'], ['Users.User_ID'], name=op.f('Points_ibfk_1')),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('WISHLIST_ITEMS')
    # ### end Alembic commands ###
