# migrations/versions/72bccb459ba1_add_store_settings_table.py

"""Add store settings table

Revision ID: 72bccb459ba1
Revises: 2f5bfe168650
Create Date: 2025-09-22 20:01:29.136458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bccb459ba1'
down_revision = '2f5bfe168650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('STORE_SETTINGS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebay_category_id', sa.String(length=50), nullable=False),
    sa.Column('point_ratio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('STORE_SETTINGS')
    # ### end Alembic commands ###
