"""Add Address model

Revision ID: 988d6fbccf58
Revises: 60f2906749db
Create Date: 2025-10-07 03:03:31.988225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988d6fbccf58'
down_revision = '60f2906749db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADDRESSES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.USER_CODE'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ADDRESSES')
    # ### end Alembic commands ###