"""add LOCKED_REASON to users

Revision ID: 9dbfcc4fe50e
Revises: 65f94b714712
Create Date: 2025-10-15 11:08:27.653587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dbfcc4fe50e'
down_revision = '65f94b714712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADDRESSES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.USER_CODE'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.drop_column('LICENSE_NUMBER')

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LOCKED_REASON', sa.String(length=255), nullable=True))
        batch_op.drop_column('SESSION_MINUTES_OVERRIDE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SESSION_MINUTES_OVERRIDE', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('LOCKED_REASON')

    with op.batch_alter_table('DRIVER_APPLICATIONS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LICENSE_NUMBER', mysql.VARCHAR(length=50), nullable=True))

    op.drop_table('ADDRESSES')
    # ### end Alembic commands ###
