"""Remove temporary points column after data migration

Revision ID: c17918916cb3
Revises: ef96a8fd432f
Create Date: 2025-10-16 12:15:48.340489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c17918916cb3'
down_revision = 'ef96a8fd432f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_column('POINTS')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('POINTS', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
