"""Add CartItem table

Revision ID: ccbaaf7662b7
Revises: dd0cccc42682
Create Date: 2025-09-30 04:06:23.259850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccbaaf7662b7'
down_revision = 'dd0cccc42682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CART_ITEMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.USER_CODE'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('DRIVER_APPLICATIONS')
    op.drop_table('Users')
    op.drop_table('Orders')
    op.drop_table('Point_Rules')
    op.drop_table('Points')
    op.drop_table('SPONSORS')
    op.drop_table('DRIVERS')
    op.drop_table('Application')
    op.drop_table('ADMIN')
    op.drop_table('Invoice')
    op.drop_table('API_Rules')
    op.drop_table('Organizations')
    with op.batch_alter_table('ABOUT_INFO', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=mysql.TINYTEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('USERNAME',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('FNAME',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('LNAME',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('EMAIL',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('CREATED_AT',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('IS_ACTIVE',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('IS_LOCKED_OUT',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.create_unique_constraint(None, ['USERNAME'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('IS_LOCKED_OUT',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('IS_ACTIVE',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('CREATED_AT',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('EMAIL',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('LNAME',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('FNAME',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('USERNAME',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)

    with op.batch_alter_table('ABOUT_INFO', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=255),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)

    op.create_table('Organizations',
    sa.Column('Org_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Org_Name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Org_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('API_Rules',
    sa.Column('ARule_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Rule_Desc', mysql.TEXT(), nullable=True),
    sa.Column('Org_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Org_ID'], ['Organizations.Org_ID'], name=op.f('fk_arules_app')),
    sa.PrimaryKeyConstraint('ARule_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Invoice',
    sa.Column('Invoice_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Order_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Order_ID'], ['Orders.Order_ID'], name=op.f('Invoice_ibfk_1')),
    sa.PrimaryKeyConstraint('Invoice_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ADMIN',
    sa.Column('ADMIN_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ROLE_TITLE', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ADMIN_ID'], ['USERS.USER_CODE'], name=op.f('ADMIN_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ADMIN_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Application',
    sa.Column('App_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('App_Name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('App_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('DRIVERS',
    sa.Column('DRIVER_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('LICENSE_NUMBER', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['DRIVER_ID'], ['USERS.USER_CODE'], name='DRIVERS_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('DRIVER_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('SPONSORS',
    sa.Column('SPONSOR_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ORG_NAME', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('STATUS', mysql.ENUM('Pending', 'Approved', 'Rejected'), server_default=sa.text("'Pending'"), nullable=True),
    sa.ForeignKeyConstraint(['SPONSOR_ID'], ['USERS.USER_CODE'], name='SPONSORS_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SPONSOR_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Points',
    sa.Column('User_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Points_Value', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['User_ID'], ['Users.User_ID'], name=op.f('Points_ibfk_1')),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Point_Rules',
    sa.Column('PRule_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Rule_Desc', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('PRule_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Orders',
    sa.Column('Order_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('User_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['User_ID'], ['Users.User_ID'], name=op.f('Orders_ibfk_1')),
    sa.PrimaryKeyConstraint('Order_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Users',
    sa.Column('User_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('User_Fname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('User_Lname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('User_Role', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('User_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('DRIVER_APPLICATIONS',
    sa.Column('APPLICATION_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('DRIVER_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SPONSOR_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('STATUS', mysql.ENUM('Pending', 'Accepted', 'Rejected'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('REASON', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('APPLIED_AT', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['DRIVER_ID'], ['DRIVERS.DRIVER_ID'], name=op.f('DRIVER_APPLICATIONS_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SPONSOR_ID'], ['SPONSORS.SPONSOR_ID'], name=op.f('DRIVER_APPLICATIONS_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('APPLICATION_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('CART_ITEMS')
    # ### end Alembic commands ###
