"""Add CartItem table

Revision ID: ccbaaf7662b7
Revises: dd0cccc42682
Create Date: 2025-09-30 04:06:23.259850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccbaaf7662b7'
down_revision = 'dd0cccc42682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CART_ITEMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.USER_CODE'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('ABOUT_INFO', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=mysql.TINYTEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('USERNAME',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('FNAME',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('LNAME',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('EMAIL',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('CREATED_AT',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('IS_ACTIVE',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('IS_LOCKED_OUT',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.create_unique_constraint(None, ['USERNAME'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###