"""Initial migration with multi-sponsor architecture

Revision ID: ef96a8fd432f
Revises: 
Create Date: 2025-10-16 12:06:25.346459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef96a8fd432f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CART_ITEMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['SPONSORS.SPONSOR_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.USER_CODE'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DRIVER_SPONSOR_ASSOCIATIONS',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['DRIVERS.DRIVER_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['SPONSORS.SPONSOR_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('driver_id', 'sponsor_id')
    )
    op.create_table('PURCHASES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['SPONSORS.SPONSOR_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.USER_CODE'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('STORE_SETTINGS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('ebay_category_id', sa.String(length=50), nullable=False),
    sa.Column('point_ratio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['SPONSORS.SPONSOR_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sponsor_id')
    )
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_column('POINTS')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('POINTS', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))

    op.drop_table('STORE_SETTINGS')
    op.drop_table('PURCHASES')
    op.drop_table('DRIVER_SPONSOR_ASSOCIATIONS')
    op.drop_table('CART_ITEMS')
    # ### end Alembic commands ###
